### ISSUE TITLE
Switch to renjin ?

### ISSUE THREAD

**Issue by hinerm** [scijava/scripting-r#2]
Mavenized R scripting engine in Java:

http://www.renjin.org/downloads.html

**Comment by hinerm** [comment]
yep it's a JSR223 script engine and so we should just use it!

**Comment by hinerm** [comment]
what about the other direction..?

**Comment by hinerm** [comment]
switched. done

**Comment by jefferis** [comment]
Thanks @hinerm, I will be keen to see how this progresses. However a comment: do you have any experience of using R packages with renjin? I do not yet, but I am assuming that only pure R packages have a chance of working and that anything relying on compiled code will break. Best wishes, Greg.

**Comment by hinerm** [comment]
@jefferis I personally haven't tried it, but it looks like they have [a significant list of compatible packages already](http://packages.renjin.org/). They are distributed via Maven so I expect it is reasonable to try them locally. I haven't thought about how to expose them in ImageJ/Fiji though.

**Comment by jefferis** [comment]
Thanks for the link. That essentially confirms what I thought. For my own packages I have a lot of difficulty avoiding any dependencies with compiled code. But I am still happy to see this progress. Best, Greg.

**Comment by ctrueden** [comment]
From all appearances, the Renjin team is amazing. Check out [this blog post about packages.renjin.org](http://www.renjin.org/blog/2015-09-14-new-packages-renjin-org.html), which explains:

> One decision we’ve made with Renjin is to focus on compiling the native C and Fortran code present in some CRAN packages to JVM bytecode rather than building an integration based on calling out of the JVM and into native binaries.
>
> The downside is that it will be awhile before I get to use my favorite geostatistical packages with Renjin, because our compiler can’t handle C code as complex as gdal yet.
>
> The upside is that a package once built for Renjin encapsulates all of its dependencies, and can be effortlessly used on any platform: Linux, Mac OS X, Windows, wherever there’s a JVM available, and you’ll never have to spend a sleepless night trying to get a Fortran compiler to build on some random version of Solaris on your client’s backoffice system so you can for the love of god please just get randomForest running!!

Totally amazing stuff.

**Comment by LeeKamentsky** [comment]
For me personally, scripting in Renjin would be a no-go, similar to Jython. Key elements are non-support for Rcpp (a c++ / R bridging library) and packages it depends on, most notably for me, dplyr. It looks like integrating Renjin scripting is an easy no-brainer, but R's power is largely the breadth of its packages and often their focus on very narrow domains (e.g. analysis of Affymetrix chip data). Perhaps as Renjin matures, package authors will make compatibility with it a priority and perhaps Renjin's C to JVM compiler will make that easier to achieve, but now, too many missing pieces for too many uses.
